### ISSUE TITLE
Video Screen Stopped

### ISSUE THREAD

**Issue by thesurajdas** [thesurajdas/text-editor-sign-language#1]
### When we run model.py hand gesture box is greater than the fixed size the live webcam is paused and does not work.
Error Details:
> [!WARNING]
> Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?28f30a56-4bfe-4760-a888-b3ce4a6ae823) or open in a [text editor](command:workbench.action.openLargeOutput?28f30a56-4bfe-4760-a888-b3ce4a6ae823). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\Users\Suraj Das\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "c:\Users\Suraj Das\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 861, in callit
    func(*args)
  File "C:\Users\Suraj Das\AppData\Local\Temp\ipykernel_8900\277348408.py", line 54, in update_frame
    imgResize = cv2.resize(imgCrop, (wCal, imgSize))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.8.0) [D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4062](file:///D:/a/opencv-python/opencv-python/opencv/modules/imgproc/src/resize.cpp:4062): error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

**Comment by vibhorjoshi** [comment]
Please assign it to me

**Comment by thesurajdas** [comment]
Sure now you can contribute.

**Comment by vibhorjoshi** [comment]
Can you please guide me on how to contribute 🙏 as I don't know the
procedure

**Comment by thesurajdas** [comment]
1. Check documentation to know about the project.
2. Fork and Clone this repo.
3. Create a new branch of your forked repo.
4. Install python and these libraries:

![image](https://github.com/thesurajdas/text-editor-sign-language/assets/44750499/3ed1d210-e815-4c2e-ac67-5cb0caa22680)
5. Run model.py (Use VSCode) file by using this command " python model.py".
6. It takes some time to run the program and then up your hand on the camera and check the camera stops and your hand is close to the camera.
7. Also check the terminal for the error after the program stops automatically.
8. Check the comment lines of the code and fix the bug and create pull request.

![image](https://github.com/thesurajdas/text-editor-sign-language/assets/44750499/758b002a-d7bd-450c-9f90-8d2705725ce1)
You can start working from this line of code.

**Comment by vibhorjoshi** [comment]
Thanks, I'll check it out.

**Comment by vibhorjoshi** [comment]
I have solved the issue but i am not able to merge it

**Comment by thesurajdas** [comment]
Check your pull request branch properly and then I will check. If your updated code is good then I can merge your branch with the main branch.
